#!/bin/bash

[ $(ls dump/ | wc -l) -lt 1 ] && {
    echo "No dumps no reports"
    exit 0
}

rm -rf latest-*
lastDumpName=`ls -lah dump/ | tail -n1 | rev | cut -d' ' -f1 | rev `
lastDumpTimestamp=$(echo $lastDumpName | cut -d '-' -f1 )
cp -rf dump/$lastDumpTimestamp* .


if [ $(rename --version | rev | cut -d' ' -f1 | rev | tr -d "." ) -lt 2282 ] ; then
    rename "s/$lastDumpTimestamp/latest/" $lastDumpTimestamp-*
else
    rename "$lastDumpTimestamp" 'latest' $lastDumpTimestamp-*
fi

echo '
set term png
set output "latest-objective.png"
plot "latest-objective" using 1  title "Best" with lines, \
"" using 2 title "Average" with lines
' | gnuplot
