#!/bin/bash

rm -rf latest-*
lastDumpName=`ls -lah dump/ | tail -n1 | rev | cut -d' ' -f1 | rev `
lastDumpTimestamp=$(cut -d '-' -f1 <<< $lastDumpName)
cp -rf dump/$lastDumpTimestamp* .

rename "$lastDumpTimestamp" 'latest' $lastDumpTimestamp-*

[ -f latest-scalar_attr ] && {
    echo '
    set term png
    set output "latest-scalar_attr.png"
    plot "latest-scalar_attr" using 3  title "Pulse Rate" with lines,  \
         "" using 4 title "Loudness" with lines
    ' | gnuplot
    xdg-open latest-scalar_attr.png
}

[ -f latest-objective ] && {
    echo '
    set term png
    set output "latest-objective.png"
    plot "latest-objective" using 1  title "Best" with lines, \
    "" using 2 title "Average" with lines, \
    "" using 3 title "Worst" with lines
    ' | gnuplot
    xdg-open latest-objective.png
}


notify-send "Execution finished"
